# -*- coding: utf-8 -*-
"""Parabola.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkCF2HUhdawgYfS96CdKjp0xS9OjugxP
"""



import numpy as np
import matplotlib.pyplot as plt

# Solicita os parâmetros da função de segundo grau ao usuário
print("Insira os parâmetros da função de segundo grau (ax^2 + bx + c):")
a = float(input("Digite o valor de 'a': "))
b = float(input("Digite o valor de 'b': "))
c = float(input("Digite o valor de 'c': "))

# Gera valores de x para o gráfico
x = np.linspace(-10, 10, 400) # De -10 a 10 com 400 pontos

# Calcula os valores de y usando a função de segundo grau
y = a * x**2 + b * x + c

# Cria o gráfico
plt.figure(figsize=(8, 6))
plt.plot(x, y, label=f'{a}x² + {b}x + {c}')

# Adiciona título e rótulos
plt.title('Gráfico de uma Função de Segundo Grau')
plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')
plt.grid(True)
plt.axhline(0, color='black',linewidth=0.5) # Eixo X em y=0
plt.axvline(0, color='black',linewidth=0.5) # Eixo Y em x=0
plt.legend()
plt.show()